name: Create Release for Version Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: hello-linux
          - os: macOS-latest
            output-name: hello-mac
          - os: windows-latest
            output-name: hello-windows.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release_${{ matrix.output-name }}.txt
      - name: Test
        run: cat Release_${{ matrix.output-name }}.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release_${{ matrix.output-name }}.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      


       
