name: Create Release for Version Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: github-api_linux-gnu
          - os: macOS-latest
            output-name: github-api_darwin
          - os: windows-latest
            output-name: github-api.exe

    steps:
      - name: Install Dart
        uses: DanTup/gh-actions/setup-dart@master
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: dart pub get
        
      - name: Compile binary file
        run: dart2native bin/github_api.dart -v -o build/${{ matrix.output-name }}
          
      - uses: actions/upload-artifact@v1
        with:
          name: native-executables
          path: build
       
