name: Update latest release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: dart pub get
        
      - name: Build binary file
        run: mkdir build/ && dart2native bin/github_api.dart -o github-api_ubuntu

      - name: Update latest Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: latest
          files: ./github-api_ubuntu     
